'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const Config=require('../addin/config.js');
let chromium;try{chromium=require('playwright').chromium;}catch{}
const uiTest=chromium?test:test.skip;
function copy(value){return JSON.parse(JSON.stringify(value));}
function fixture(current){current=current||Config.modernDefaults();return {revision:7,activeTemplateID:'builtin',templates:[{id:'builtin',name:'默认文书',config:copy(current)}],current:copy(current)};}
async function browserFixture(t,options={}){
 const launch=process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE?{executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE}:fs.existsSync('/Applications/Google Chrome.app/Contents/MacOS/Google Chrome')?{channel:'chrome'}:{};
 const browser=await chromium.launch({...launch,headless:true});t.after(()=>browser.close());const page=await browser.newPage({viewport:{width:940,height:1000}}),calls=[],errors=[];page.on('pageerror',e=>errors.push(e.message));t.after(()=>assert.deepEqual(errors,[]));
 const ownerResults=new Map();let settings=options.settings||fixture(),result={},requestID=0,lastOperation='',environment=options.environment||{server:{ok:true,version:'1.2.0-beta.1'},wps:{heartbeatFresh:true,apiReady:true,documentOpen:true,bridgeVersion:'1.2.0-beta.1',version:'12.1.28496',docID:'12',scope:'document'},fonts:{ready:true,values:['华文中宋','仿宋_GB2312'],missing:[]}};
 const analysis=options.analysis||{docID:'12',fingerprint:'fingerprint',scope:'document',paragraphs:[{index:1,summary:'通知标题',role:'title',reason:'首个非空段落',eligible:true},{index:2,summary:'收件人：',role:'body',reason:'正文规则',eligible:true},{index:3,summary:'表格内容',role:'preserve',reason:'表格不处理',eligible:false,assignable:false},{index:4,summary:'',role:'blank',reason:'空段：分页按规则',eligible:false,assignable:true}],sessionInvalidated:false};
 await page.route('http://127.0.0.1:18999/**',async route=>{
  const req=route.request(),url=new URL(req.url()),pathname=url.pathname,body=req.method()==='POST'?req.postDataJSON():undefined,headers=req.headers(),clientID=headers['x-formatter-client']||'',ownerEnvironment=options.owners&&options.owners[clientID]||environment;calls.push({pathname,body,headers});let output,status=200;
  if(Object.prototype.hasOwnProperty.call(headers,'x-formatter-client')&&!headers['x-formatter-client']){await route.fulfill({status:400,contentType:'application/json',body:JSON.stringify({error:'插件实例标识为空，请从目标文档重新打开此窗口。'})});return;}
  if(pathname==='/session')output={token:'ui-synthetic-only'};
  else if(pathname==='/settings')output=settings;
  else if(pathname==='/fonts')output={fonts:ownerEnvironment.fonts.values||[]};
  else if(pathname==='/environment'){if(options.hangEnvironment)return;output=ownerEnvironment;}
  else if(pathname==='/settings/save'){settings.current=copy(body.config);settings.revision++;output=settings;}
  else if(pathname==='/templates'){settings.current=copy(body.config);settings.activeTemplateID='new';settings.templates.push({id:'new',name:body.name,config:copy(body.config)});settings.revision++;output=settings;}
  else if(pathname==='/templates/export'){const config=copy(settings.templates.find(v=>v.id===body.id).config);if(!body.includeFurniture){['header','footer'].forEach(k=>{config.furniture[k].text='';config.furniture[k].enabled=false;});}output={format:'wps-local-formatter-template',fileVersion:1,name:'默认文书',config};}
  else if(pathname==='/templates/import'){settings.templates.push({id:'imported',name:body.name||body.payload.name,config:copy(body.payload.config)});settings.revision++;output=settings;}
  else if(pathname==='/request'){
   if(body.op==='set-role'&&options.roleTransport){if(options.roleTransport==='failed')await route.abort('failed');return;}
   if(body.op==='set-role'&&options.roleError){await route.fulfill({status:409,contentType:'application/json',body:JSON.stringify({error:options.roleError})});return;}
   const id=++requestID;lastOperation=body.op;result={id,ok:true};
   if(body.op==='analyze')result.analysis=copy(analysis);
   else if(body.op==='set-role'){const row=analysis.paragraphs.find(p=>p.index===body.index);row.role=body.role==='auto'?'blank':body.role;result.analysis=copy(analysis);}
   else if(body.op==='scope'){analysis.scope=body.scope;ownerEnvironment.wps.scope=body.scope;result.analysis=copy(analysis);}
   else if(body.op==='extract')result.extracted={format:{font:null,size:12,alignment:0,indent:null,line:{mode:null,value:null},before:0,after:null},warnings:['混合字体保持原样']};
   else if(body.op==='preview')result.preview={scope:analysis.scope,targetCount:3,counts:{change:2,skip:1,unchanged:1},warnings:[],rows:[{index:1,summary:'通知标题',eligible:true,selected:true,change:true,reason:'标题格式'},{index:2,summary:'收件人：',eligible:true,selected:true,change:false,reason:'当前格式相同'},{index:3,summary:'表格内容',eligible:false,selected:true,skip:true,reason:'表格不处理'},{index:4,summary:'',role:'blank',eligible:false,selected:true,skip:false,change:true,reason:'空段：仅链接分页'}]};
   ownerResults.set(body.clientID||'',result);if(body.op==='set-role'&&options.roleResponseLoss){await route.abort('failed');return;}output={id};
  }else if(pathname==='/state'){if(lastOperation==='set-role'&&options.rolePoll403){await route.fulfill({status:403,contentType:'application/json',body:JSON.stringify({error:'服务重启后令牌已失效。'})});return;}if(options.stateTransport==='failed'||lastOperation==='set-role'&&options.rolePollLoss){await route.abort('failed');return;}output={status:ownerEnvironment.wps,result:clientID?options.queueResults&&options.queueResults[clientID]||ownerResults.get(clientID)||{}:options.foreignResult?{id:requestID,ok:false,message:'其他窗口没有打开文档'}:result,uiResult:options.uiResults&&options.uiResults[clientID]};}
  else if(/^\/[a-z-]+\.(html|js|css)$/.test(pathname)){
   const file=path.join(__dirname,'..','addin',pathname.slice(1));if(fs.existsSync(file)){await route.fulfill({status:200,contentType:pathname.endsWith('.html')?'text/html':pathname.endsWith('.css')?'text/css':'text/javascript',body:fs.readFileSync(file)});return;}status=404;output={error:'missing resource'};
  }else {status=404;output={error:'unknown synthetic endpoint'};}
  await route.fulfill({status,contentType:'application/json',body:JSON.stringify(output)});
 });
 return {page,calls,environment,analysis,get settings(){return settings;}};
}
uiTest('旧模板保存保留迁移后的字段，新建与另存为使用不同默认',async t=>{
 const f=await browserFixture(t,{settings:fixture(Config.defaults())});await f.page.goto('http://127.0.0.1:18999/settings.html');await f.page.waitForFunction(()=>!document.getElementById('save').disabled);
 await f.page.locator('#save').click();await f.page.locator('#feedback').filter({hasText:'设置已保存'}).waitFor();let saved=f.calls.find(c=>c.pathname==='/settings/save').body.config;assert.equal(saved.version,2);assert.equal(saved.recognition,'position');assert.equal(saved.pagination.headingFollow,null);assert.equal(saved.headings.length,9);
 await f.page.locator('#duplicateTemplate').click();await f.page.locator('#templateName').fill('复制模板');await f.page.locator('#confirmTemplate').click();await f.page.locator('#feedback').filter({hasText:'模板已保存'}).waitFor();assert.equal(f.calls.filter(c=>c.pathname==='/templates').at(-1).body.config.recognition,'position');
 await f.page.locator('#newTemplate').click();await f.page.locator('#templateName').fill('新模板');await f.page.locator('#confirmTemplate').click();await f.page.locator('#feedback').filter({hasText:'模板已保存'}).waitFor();saved=f.calls.filter(c=>c.pathname==='/templates').at(-1).body.config;assert.equal(saved.recognition,'styles');assert.equal(saved.pagination.headingFollow,true);assert.equal(saved.pagination.bodyWidow,true);assert.equal(saved.lists.protect,true);
});
uiTest('格式提取只填草稿，混合值保持原样，并显示统一段距覆盖提示',async t=>{
 const f=await browserFixture(t);await f.page.goto('http://127.0.0.1:18999/settings.html');await f.page.waitForFunction(()=>!document.getElementById('save').disabled);await f.page.locator('[data-capture=title]').click();await f.page.locator('#feedback').filter({hasText:'格式已填入草稿'}).waitFor();assert.equal(await f.page.locator('#title-font').inputValue(),'');assert.equal(await f.page.locator('#title-size').inputValue(),'12');assert.match(await f.page.locator('#feedback').textContent(),/全篇段落仍会覆盖/);assert.equal(f.calls.filter(c=>c.pathname==='/settings/save').length,0);assert.deepEqual(f.calls.find(c=>c.pathname==='/request').body,{op:'extract',role:'title',docID:'12'});
});
uiTest('环境检查挂起时结构分析、标记、预览和提取仍通过实例状态完成',async t=>{
 const owner={wps:{heartbeatFresh:true,apiReady:true,documentOpen:true,docID:'12',scope:'document'},fonts:{ready:true,values:[],missing:[]}},hash='#clientID=client-A&docID=12';
 const f=await browserFixture(t,{hangEnvironment:true,owners:{'client-A':owner}});await f.page.goto('http://127.0.0.1:18999/structure.html'+hash);await f.page.locator('#paragraphRows select').first().waitFor();
 await f.page.evaluate(()=>{window.environmentFinished=false;fetch('/environment',{headers:{'X-Formatter-Client':'client-A'}}).then(()=>{window.environmentFinished=true;}).catch(()=>{});});
 await f.page.locator('#paragraphRows select[data-index="2"]').selectOption('preserve');await f.page.locator('#feedback').filter({hasText:'角色已标记'}).waitFor();await f.page.locator('#preview').click();await f.page.locator('#previewPanel').waitFor({state:'visible'});assert.match(await f.page.locator('#previewSummary').textContent(),/预计修改 2 段/);
 const stateCalls=f.calls.filter(c=>c.pathname==='/state').length;owner.wps.sessionInvalidated=true;await f.page.locator('#invalidated').waitFor({state:'visible'});assert.ok(f.calls.filter(c=>c.pathname==='/state').length>stateCalls);assert.equal(await f.page.locator('#paragraphRows select').first().isDisabled(),true);assert.equal(await f.page.evaluate(()=>window.environmentFinished),false);owner.wps.sessionInvalidated=false;
 await f.page.goto('http://127.0.0.1:18999/settings.html'+hash);await f.page.waitForFunction(()=>!document.getElementById('save').disabled);await f.page.locator('[data-capture=title]').click();await f.page.locator('#feedback').filter({hasText:'格式已填入草稿'}).waitFor();assert.equal(await f.page.locator('#title-size').inputValue(),'12');
 assert.deepEqual(f.calls.filter(c=>c.pathname==='/request').map(c=>c.body.op),['analyze','set-role','preview','extract']);assert.equal(f.calls.filter(c=>c.pathname==='/environment').length,1);for(const call of f.calls.filter(c=>c.pathname==='/state'||c.pathname==='/request')){assert.equal(call.headers['x-formatter-client'],'client-A');if(call.body){assert.equal(call.body.clientID,'client-A');assert.equal(call.body.docID,'12');}}
});
uiTest('结构连接过期时拒绝请求并保留人工标记，重连后继续，真实关闭才失效',async t=>{
 const owner={wps:{heartbeatFresh:true,apiReady:true,documentOpen:true,docID:'12',scope:'document'},fonts:{ready:true,values:[],missing:[]}},f=await browserFixture(t,{owners:{'client-A':owner}});await f.page.goto('http://127.0.0.1:18999/structure.html#clientID=client-A&docID=12');const role=f.page.locator('#paragraphRows select[data-index="2"]');await role.waitFor();await role.selectOption('preserve');await f.page.locator('#feedback').filter({hasText:'角色已标记'}).waitFor();const before=f.calls.filter(c=>c.pathname==='/request').length;
 Object.assign(owner.wps,{heartbeatFresh:false,apiReady:false,documentOpen:false,docID:'99',sessionInvalidated:true});await f.page.locator('#feedback').filter({hasText:'等待 WPS 插件连接'}).waitFor();assert.equal(await f.page.locator('#invalidated').isVisible(),false);assert.equal(await role.inputValue(),'preserve');assert.equal(await role.isDisabled(),false);assert.equal(f.calls.filter(c=>c.pathname==='/request').length,before);
 await role.selectOption('addressee');await f.page.locator('#feedback').filter({hasText:'等待 WPS 插件连接'}).waitFor();await f.page.waitForFunction(()=>!document.querySelector('#paragraphRows select[data-index="2"]').disabled);assert.equal(await role.inputValue(),'preserve');assert.equal(await f.page.locator('#invalidated').isVisible(),false);await f.page.locator('#preview').click();await f.page.locator('#feedback').filter({hasText:'等待 WPS 插件连接'}).waitFor();assert.equal(f.calls.filter(c=>c.pathname==='/request').length,before);assert.ok(!/关闭或切换/.test(await f.page.locator('#feedback').textContent()));
 Object.assign(owner.wps,{heartbeatFresh:true,apiReady:true,documentOpen:true,docID:'12',sessionInvalidated:false});await role.selectOption('addressee');await f.page.locator('#feedback').filter({hasText:'角色已标记'}).waitFor();assert.equal(await role.inputValue(),'addressee');assert.equal(await f.page.locator('#invalidated').isVisible(),false);assert.deepEqual(f.calls.filter(c=>c.pathname==='/request').map(c=>c.body.op),['analyze','set-role','set-role']);
 const reconnected=f.calls.filter(c=>c.pathname==='/request').length;owner.wps.documentOpen=false;await f.page.locator('#preview').click();await f.page.locator('#feedback').filter({hasText:'关闭后重新打开此窗口'}).waitFor();assert.equal(f.calls.filter(c=>c.pathname==='/request').length,reconnected);await f.page.locator('#invalidated').waitFor({state:'visible'});assert.equal(await role.isDisabled(),true);
});
uiTest('提取先验证心跳和 API，未知时等待，重连可用且真实关闭仍拒绝',async t=>{
 const owner={wps:{heartbeatFresh:false,apiReady:false,documentOpen:false,docID:'99'},fonts:{ready:false,values:[],missing:[]}},f=await browserFixture(t,{owners:{'client-A':owner}});await f.page.goto('http://127.0.0.1:18999/settings.html#clientID=client-A&docID=12');await f.page.waitForFunction(()=>!document.getElementById('save').disabled);const font=await f.page.locator('#title-font').inputValue();
 for(const connection of [{heartbeatFresh:false,apiReady:false},{heartbeatFresh:true,apiReady:false},{heartbeatFresh:undefined,apiReady:undefined}]){Object.assign(owner.wps,connection);await f.page.locator('[data-capture=title]').click();await f.page.locator('#feedback').filter({hasText:'等待 WPS 插件连接'}).waitFor();assert.ok(!/关闭或切换/.test(await f.page.locator('#feedback').textContent()));assert.equal(f.calls.filter(c=>c.pathname==='/request').length,0);assert.equal(await f.page.locator('#title-font').inputValue(),font);}
 Object.assign(owner.wps,{heartbeatFresh:true,apiReady:true,documentOpen:true,docID:'12'});await f.page.locator('[data-capture=title]').click();await f.page.locator('#feedback').filter({hasText:'格式已填入草稿'}).waitFor();assert.equal(await f.page.locator('#title-size').inputValue(),'12');assert.deepEqual(f.calls.find(c=>c.pathname==='/request').body,{op:'extract',role:'title',docID:'12',clientID:'client-A'});
 owner.wps.documentOpen=false;await f.page.locator('[data-capture=title]').click();await f.page.locator('#feedback').filter({hasText:'关闭后重新打开此窗口'}).waitFor();assert.equal(f.calls.filter(c=>c.pathname==='/request').length,1);
});
uiTest('角色请求发送前可等连接，发送后网络失败或超时需重分析，结构变化仍失效',async t=>{
 const options={},f=await browserFixture(t,options);await f.page.goto('http://127.0.0.1:18999/structure.html');const role=f.page.locator('#paragraphRows select[data-index="2"]');await role.waitFor();await role.selectOption('preserve');await f.page.locator('#feedback').filter({hasText:'角色已标记'}).waitFor();
 const before=f.calls.filter(c=>c.pathname==='/request').length;options.stateTransport='failed';await role.selectOption('addressee');await f.page.locator('#feedback').filter({hasText:'等待 WPS 插件连接'}).waitFor();await f.page.waitForFunction(()=>!document.querySelector('#paragraphRows select[data-index="2"]').disabled);assert.equal(await role.inputValue(),'preserve');assert.equal(await f.page.locator('#invalidated').isVisible(),false);assert.equal(f.calls.filter(c=>c.pathname==='/request').length,before);options.stateTransport=null;
 for(const transport of ['failed','timeout']){options.roleTransport=transport;await role.selectOption('addressee');await f.page.locator('#feedback').filter({hasText:'结果尚未确认，请重新分析'}).waitFor();assert.equal(await role.inputValue(),'preserve');assert.equal(await role.isDisabled(),true);assert.equal(f.analysis.paragraphs.find(p=>p.index===2).role,'preserve');assert.match(await f.page.locator('#invalidatedMessage').textContent(),/已有标记未清除/);assert.ok(!/已失效|已变化/.test(await f.page.locator('#invalidated').textContent()));options.roleTransport=null;await f.page.locator('#analyze').click();await f.page.locator('#feedback').filter({hasText:'已读取。'}).waitFor();assert.equal(await role.isDisabled(),false);assert.equal(await f.page.locator('#invalidated').isVisible(),false);}
 await role.selectOption('addressee');await f.page.locator('#feedback').filter({hasText:'角色已标记'}).waitFor();assert.equal(await role.inputValue(),'addressee');assert.equal(await f.page.locator('#invalidated').isVisible(),false);
 options.roleError='文档结构已变化，请重新分析。';await role.selectOption('preserve');await f.page.locator('#invalidated').waitFor({state:'visible'});assert.match(await f.page.locator('#invalidatedMessage').textContent(),/文档结构已变化/);assert.equal(await role.isDisabled(),true);
});
uiTest('角色已执行但响应或结果轮询丢失时停用纠正，重分析回读实际角色',async t=>{
 const options={},f=await browserFixture(t,options);await f.page.goto('http://127.0.0.1:18999/structure.html#clientID=client-A&docID=12');const role=f.page.locator('#paragraphRows select[data-index="2"]');await role.waitFor();await role.selectOption('preserve');await f.page.locator('#feedback').filter({hasText:'角色已标记'}).waitFor();
 for(const loss of [{key:'roleResponseLoss',prior:'preserve',next:'addressee'},{key:'rolePollLoss',prior:'addressee',next:'preserve'},{key:'rolePoll403',prior:'preserve',next:'addressee'}]){options[loss.key]=true;await role.selectOption(loss.next);await f.page.locator('#feedback').filter({hasText:'结果尚未确认，请重新分析'}).waitFor();assert.equal(f.analysis.paragraphs.find(p=>p.index===2).role,loss.next);assert.equal(f.analysis.sessionInvalidated,false);assert.equal(await role.inputValue(),loss.prior);assert.equal(await role.isDisabled(),true);assert.match(await f.page.locator('#invalidatedMessage').textContent(),/上次已确认的角色/);assert.ok(!/已失效|已变化/.test(await f.page.locator('#invalidated').textContent()));await f.page.locator('#rowFilter').selectOption('all');assert.equal(await role.isDisabled(),true);
  options[loss.key]=false;await f.page.locator('#analyze').click();await f.page.locator('#feedback').filter({hasText:'已读取。'}).waitFor();assert.equal(await role.inputValue(),loss.next);assert.equal(await role.isDisabled(),false);assert.equal(await f.page.locator('#invalidated').isVisible(),false);
 }
 for(const call of f.calls.filter(c=>c.pathname==='/request')){assert.equal(call.body.clientID,'client-A');assert.equal(call.body.docID,'12');}assert.equal(f.calls.filter(c=>c.pathname==='/request'&&c.body.op==='set-role').length,4);
});
uiTest('分享默认去掉页眉页脚，导入同名可改名且不切换或应用',async t=>{
 const initial=fixture();initial.current.furniture.header.text='内部页眉';initial.current.furniture.header.enabled=true;initial.templates[0].config=copy(initial.current);const f=await browserFixture(t,{settings:initial});await f.page.goto('http://127.0.0.1:18999/settings.html');await f.page.waitForFunction(()=>!document.getElementById('save').disabled);
 const download=f.page.waitForEvent('download');await f.page.locator('#exportTemplate').click();const artifact=await download;const payload=JSON.parse(fs.readFileSync(await artifact.path(),'utf8'));assert.equal(payload.config.furniture.header.text,'');assert.equal(payload.config.furniture.header.enabled,false);assert.equal(f.calls.find(c=>c.pathname==='/templates/export').body.includeFurniture,false);assert.equal(payload.id,undefined);
 const imported={format:'wps-local-formatter-template',fileVersion:1,name:'默认文书',config:Config.modernDefaults()};await f.page.locator('#title-font').fill('用户未保存的草稿字体');await f.page.locator('#importFile').setInputFiles({name:'template.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(imported))});await f.page.locator('#importDraft').waitFor({state:'visible'});await f.page.locator('#importTemplate').click();assert.match(await f.page.locator('#importError').textContent(),/同名/);assert.equal(f.calls.filter(c=>c.pathname==='/templates/import').length,0);await f.page.locator('#importName').fill('外部模板');await f.page.locator('#importTemplate').click();await f.page.locator('#shareStatus').filter({hasText:'模板已追加'}).waitFor();assert.equal(f.settings.activeTemplateID,'builtin');assert.equal(await f.page.locator('#title-font').inputValue(),'用户未保存的草稿字体');assert.equal(f.calls.filter(c=>c.pathname==='/request'||c.pathname==='/settings/save'||c.pathname==='/templates/select').length,0);
});
uiTest('结构角色可反复纠正，选区和清单只产生相应请求',async t=>{
 const f=await browserFixture(t);await f.page.goto('http://127.0.0.1:18999/structure.html');await f.page.locator('#paragraphRows select').first().waitFor();await f.page.locator('#paragraphRows select[data-index="2"]').selectOption('preserve');await f.page.locator('#feedback').filter({hasText:'角色已标记'}).waitFor();assert.equal(await f.page.locator('#paragraphRows select[data-index="2"]').inputValue(),'preserve');await f.page.locator('#paragraphRows select[data-index="2"]').selectOption('addressee');await f.page.locator('#feedback').filter({hasText:'角色已标记'}).waitFor();assert.equal(f.calls.filter(c=>c.pathname==='/request'&&c.body.op==='set-role').at(-1).body.fingerprint,'fingerprint');const blank=f.page.locator('#paragraphRows select[data-index="4"]');assert.deepEqual(await blank.locator('option').evaluateAll(nodes=>nodes.map(n=>n.value)),['auto','preserve']);assert.match(await blank.textContent(),/空段（分页按规则）/);await blank.selectOption('preserve');await f.page.locator('#feedback').filter({hasText:'角色已标记'}).waitFor();await blank.selectOption('auto');await f.page.locator('#feedback').filter({hasText:'角色已标记'}).waitFor();assert.equal(f.calls.filter(c=>c.pathname==='/request'&&c.body.op==='set-role').at(-1).body.role,'auto');await f.page.locator('[name=scope][value=selection]').check();await f.page.locator('#feedback').filter({hasText:'本次按选中段落'}).waitFor();await f.page.locator('#preview').click();await f.page.locator('#previewPanel').waitFor({state:'visible'});assert.match(await f.page.locator('#previewSummary').textContent(),/预计修改 2 段/);assert.match(await f.page.locator('#previewRows').textContent(),/无需修改/);assert.match(await f.page.locator('#previewRows').textContent(),/跳过/);assert.match(await f.page.locator('#previewRows').textContent(),/第 4 段 · 将修改 · （空段）空段：仅链接分页/);assert.ok(!f.calls.some(c=>c.pathname==='/request'&&c.body.op==='format'));
 f.environment.wps.sessionInvalidated=true;await f.page.locator('#invalidated').waitFor({state:'visible'});assert.equal(await f.page.locator('#paragraphRows select').first().isDisabled(),true);f.environment.wps.sessionInvalidated=false;f.analysis.sessionInvalidated=true;f.analysis.message='人工标记已清除，请检查下列识别结果。';await f.page.locator('#analyze').click();await f.page.locator('#feedback').filter({hasText:'人工标记已清除'}).waitFor();assert.equal(await f.page.locator('#paragraphRows select').first().isDisabled(),false);
});
uiTest('字体未知时等待，确认缺少后由用户选择并显式保存',async t=>{
 const env={server:{ok:true,version:'1.2.0-beta.1'},wps:{heartbeatFresh:false,apiReady:false,documentOpen:false},fonts:{ready:false,values:[],missing:['仿宋_GB2312']}};const f=await browserFixture(t,{environment:env});await f.page.goto('http://127.0.0.1:18999/environment.html');await f.page.locator('#feedback').filter({hasText:'环境状态已更新'}).waitFor();assert.match(await f.page.locator('#fontStatus').textContent(),/等待连接/);assert.equal(await f.page.locator('#saveFonts').isVisible(),false);assert.equal(f.calls.filter(c=>c.pathname==='/settings/save').length,0);
 env.wps={heartbeatFresh:true,apiReady:true,documentOpen:true,bridgeVersion:'1.2.0-beta.1',version:'12.1.28496'};env.fonts={ready:true,values:['华文中宋','宋体'],missing:['仿宋_GB2312']};await f.page.locator('#refresh').click();await f.page.locator('#fontStatus').filter({hasText:'缺少 1 种字体'}).waitFor();assert.match(await f.page.locator('#checks').textContent(),/插件：1.2.0-beta.1/);assert.ok(!/服务与插件版本需要处理/.test(await f.page.locator('#checks').textContent()));await f.page.locator('#saveFonts').click();assert.match(await f.page.locator('#fontFeedback').textContent(),/请为每种/);assert.equal(f.calls.filter(c=>c.pathname==='/settings/save').length,0);await f.page.locator('[data-missing-font]').selectOption('宋体');await f.page.locator('#saveFonts').click();await f.page.locator('#fontFeedback').filter({hasText:'已保存当前设置'}).waitFor();assert.equal(f.calls.find(c=>c.pathname==='/settings/save').body.config.body.font,'宋体');assert.equal(f.calls.find(c=>c.pathname==='/settings/save').body.config.title.font,'华文中宋');
});
uiTest('设置、结构和环境页在窄窗口仍能显示主要操作，无正文横向溢出',async t=>{
 const f=await browserFixture(t);for(const file of ['settings','structure','environment']){await f.page.setViewportSize({width:420,height:900});await f.page.goto('http://127.0.0.1:18999/'+file+'.html');await f.page.waitForTimeout(100);assert.equal(await f.page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth),true,file+' page overflows');assert.equal(await f.page.locator('h1').isVisible(),true);}
});
uiTest('带实例 hash 的页面只读取对应窗口，跨页导航保留实例与文档',async t=>{
 const owner={server:{ok:true,version:'1.2.0-beta.1'},wps:{heartbeatFresh:true,apiReady:true,documentOpen:true,docID:'12',bridgeVersion:'1.2.0-beta.1',scope:'document'},fonts:{ready:true,values:['华文中宋','仿宋_GB2312'],missing:[]}};
 const foreign={server:{ok:true,version:'1.2.0-beta.1'},wps:{heartbeatFresh:true,apiReady:true,documentOpen:false,docID:'99',readOnly:true},fonts:{ready:false,values:[],missing:[]}},hash='#clientID=client-A&docID=12';
 const f=await browserFixture(t,{owners:{'client-A':owner},environment:foreign,foreignResult:true});
 await f.page.goto('http://127.0.0.1:18999/settings.html'+hash);await f.page.waitForFunction(()=>!document.getElementById('save').disabled);await f.page.locator('[data-capture=title]').click();await f.page.locator('#feedback').filter({hasText:'格式已填入草稿'}).waitFor();assert.deepEqual(f.calls.find(c=>c.pathname==='/request').body,{op:'extract',role:'title',docID:'12',clientID:'client-A'});
 await f.page.getByRole('link',{name:'文档结构',exact:true}).click();await f.page.locator('#paragraphRows select').first().waitFor();assert.equal(new URL(f.page.url()).hash,hash);assert.equal(f.calls.filter(c=>c.pathname==='/request').at(-1).body.docID,'12');assert.equal(f.calls.filter(c=>c.pathname==='/request').at(-1).body.clientID,'client-A');
 await f.page.getByRole('link',{name:'环境检查',exact:true}).click();await f.page.locator('#feedback').filter({hasText:'环境状态已更新'}).waitFor();assert.equal(new URL(f.page.url()).hash,hash);assert.match(await f.page.locator('#fontStatus').textContent(),/已取得 2 种字体/);assert.match(await f.page.locator('#checks').textContent(),/会话 12/);assert.ok(!/会话 99/.test(await f.page.locator('#checks').textContent()));
 for(const call of f.calls.filter(c=>['/environment','/state','/request'].includes(c.pathname)))assert.equal(call.headers['x-formatter-client'],'client-A');
});
uiTest('固定文档关闭或切换后拒绝操作，不改为同实例的新文档',async t=>{
 const owner={server:{ok:true,version:'1.2.0-beta.1'},wps:{heartbeatFresh:true,apiReady:true,documentOpen:true,docID:'12',bridgeVersion:'1.2.0-beta.1',scope:'document'},fonts:{ready:true,values:['华文中宋','仿宋_GB2312'],missing:[]}},hash='#clientID=client-A&docID=12';
 const f=await browserFixture(t,{owners:{'client-A':owner}});await f.page.goto('http://127.0.0.1:18999/settings.html'+hash);await f.page.waitForFunction(()=>!document.getElementById('save').disabled);owner.wps.docID='99';await f.page.locator('[data-capture=title]').click();await f.page.locator('#feedback').filter({hasText:'关闭后重新打开此窗口'}).waitFor();assert.equal(f.calls.filter(c=>c.pathname==='/request').length,0);
 owner.wps.docID='12';await f.page.goto('http://127.0.0.1:18999/structure.html'+hash);await f.page.locator('#paragraphRows select').first().waitFor();const before=f.calls.filter(c=>c.pathname==='/request').length;owner.wps.documentOpen=false;await f.page.locator('#preview').click();await f.page.locator('#feedback').filter({hasText:'关闭后重新打开此窗口'}).waitFor();assert.equal(f.calls.filter(c=>c.pathname==='/request').length,before);assert.ok(!f.calls.some(c=>c.pathname==='/request'&&c.body.docID==='99'));
});
uiTest('显式空实例标识保留并拒绝，不静默转发给其他窗口',async t=>{
 const f=await browserFixture(t);for(const file of ['settings','structure','environment']){const before=f.calls.length;await f.page.goto('http://127.0.0.1:18999/'+file+'.html#clientID=&docID=12');await f.page.locator('#feedback').filter({hasText:'插件实例标识为空'}).waitFor();const apiCalls=f.calls.slice(before).filter(c=>['/settings','/environment','/state','/request'].includes(c.pathname));assert.ok(apiCalls.length>0);for(const call of apiCalls){assert.ok(Object.prototype.hasOwnProperty.call(call.headers,'x-formatter-client'));assert.equal(call.headers['x-formatter-client'],'');}assert.ok(!apiCalls.some(c=>c.pathname==='/request'));}
});
uiTest('结果页绑定窗口并优先展示该窗口 UI 结果，空 owner 不回退',async t=>{
 const uiResult={id:'ui-42',kind:'success',ok:true,changed:3,template:'当前模板：文档42模板',message:'当前文档42排版完成'},queueResult={id:'queued-other',ok:false,message:'另一个排队请求未完成'};
 const f=await browserFixture(t,{uiResults:{a:uiResult},queueResults:{a:queueResult}});await f.page.goto('http://127.0.0.1:18999/result.html#clientID=a&docID=42');await f.page.locator('#resultStatus').filter({hasText:'排版完成'}).waitFor();assert.equal(await f.page.locator('#resultMessage').textContent(),uiResult.message);assert.equal(await f.page.locator('#templateName').textContent(),'文档42模板');assert.equal(f.calls.find(c=>c.pathname==='/state').headers['x-formatter-client'],'a');assert.ok(!/另一个排队请求/.test(await f.page.locator('#resultMessage').textContent()));
 const before=f.calls.length;await f.page.goto('http://127.0.0.1:18999/result.html#clientID=&docID=42');await f.page.reload();await f.page.locator('#resultMessage').filter({hasText:'插件实例标识为空'}).waitFor();assert.equal(await f.page.locator('#resultStatus').textContent(),'无法读取结果');for(const call of f.calls.slice(before).filter(c=>c.pathname==='/session'||c.pathname==='/state')){assert.ok(Object.prototype.hasOwnProperty.call(call.headers,'x-formatter-client'));assert.equal(call.headers['x-formatter-client'],'');}
});
