(function(){
'use strict';
var binding=new URLSearchParams(window.location.hash.slice(1)),hasClientID=binding.has('clientID'),clientID=binding.get('clientID')||'',boundDocID=binding.get('docID')||'';
document.querySelectorAll('.page-links a').forEach(function(link){link.hash=window.location.hash;});
var token='',busy=false,environment=null,settings=null;
function el(tag,props,text){var n=document.createElement(tag);Object.keys(props||{}).forEach(function(k){n.setAttribute(k,props[k]);});if(text!==undefined)n.textContent=text;return n;}
function message(text,error){var n=document.getElementById('feedback');n.textContent=text;n.className=error?'failure':'';}
function api(path,data){var controller=new AbortController(),timer=setTimeout(function(){controller.abort();},8000),headers={'Content-Type':'application/json','X-Formatter-Token':token};if(hasClientID)headers['X-Formatter-Client']=clientID;return fetch(path,{method:data===undefined?'GET':'POST',signal:controller.signal,headers:headers,body:data===undefined?undefined:JSON.stringify(data)}).then(function(r){return r.json().then(function(d){if(!r.ok||d.error)throw new Error(r.status===403?'服务已更新，请关闭后重新打开环境检查。':d.error||'本地服务无法连接。');return d;});}).finally(function(){clearTimeout(timer);});}
function check(label,state,summary,action){var li=el('li');li.appendChild(el('h3',{},label));var detail=el('div');detail.appendChild(el('div',{class:'check-state','data-state':state},state==='ok'?'正常':state==='error'?'需要处理':'等待连接'));detail.appendChild(el('p',{},summary));if(action)detail.appendChild(el('p',{class:'check-action'},action));li.appendChild(detail);return li;}
function render(){var server=environment.server||{},wps=environment.wps||environment.status||{},fonts=environment.fonts||{},values=Array.isArray(fonts)?fonts:fonts.values||fonts.fonts||[],ready=!Array.isArray(fonts)&&fonts.ready===true,list=document.getElementById('checks');list.textContent='';
 list.appendChild(check('本地服务',server.ok===false?'error':'ok',server.ok===false?server.message||'服务未通过自检。':'服务已响应'+(server.version?' · '+server.version:''),server.ok===false?server.action||'运行 ZIP 内的检查入口，按提示重新初始化。':''));
 list.appendChild(check('WPS 插件心跳',wps.heartbeatFresh===true?'ok':'waiting',wps.heartbeatFresh===true?'插件近期已连接。':'尚未收到有效的近期心跳。','在 WPS 内打开“一键排版”选项卡。服务启动成功并不代表插件已连接。'));
 list.appendChild(check('WPS 文档接口',wps.apiReady===true?'ok':wps.heartbeatFresh===true?'error':'waiting',wps.apiReady===true?'文档 API 已可用。':wps.message||'等待 WPS 文档接口。',wps.apiReady===true?'':'在 WPS 中打开文档，再重新检查。'));
 var docOpen=wps.documentOpen===true||wps.docOpen===true;list.appendChild(check('当前文档',docOpen&&!wps.readOnly?'ok':wps.apiReady===true?'error':'waiting',docOpen?wps.readOnly?'当前文档只读。':'已打开文档'+(wps.docID?' · 会话 '+wps.docID:''):'尚未检测到打开的文档。',docOpen&&!wps.readOnly?'':'打开可编辑的文档。'));
 var serviceVersion=server.version||environment.version,wpsVersion=wps.bridgeVersion||wps.addinVersion,match=serviceVersion&&wpsVersion?serviceVersion===wpsVersion:null;list.appendChild(check('服务与插件版本',wps.heartbeatFresh!==true?'waiting':match===true?'ok':match===false?'error':'waiting','服务：'+(serviceVersion||'未取得')+' · 插件：'+(wpsVersion||'未取得')+(wps.version?' · WPS '+wps.version:''),match===false?'保存并自行退出 WPS，再运行初始化更新插件。':''));
 (environment.checks||[]).filter(function(item){return ['server','heartbeat','api','document','fonts','bridge-version'].indexOf(item.id)<0;}).forEach(function(item){list.appendChild(check(item.label||item.id||'环境检查',item.state==='waiting'?'waiting':item.ok===true||item.state==='ok'||item.state==='ready'?'ok':item.ok===false||item.state==='error'||item.state==='blocked'?'error':'waiting',item.message||'',item.action||''));});
 var replacements=document.getElementById('fontReplacements');replacements.textContent='';document.getElementById('saveFonts').hidden=true;var missing=fonts.missing||environment.missingFonts||[];
 if(!ready){document.getElementById('fontStatus').textContent='等待连接。尚未取得 WPS 字体列表，暂不能判断是否缺字。';}
 else if(!values.length){document.getElementById('fontStatus').textContent='WPS 字体列表为空，请重新连接后检查。';}
 else if(!missing.length){document.getElementById('fontStatus').textContent='已取得 '+values.length+' 种字体，当前设置的字体均可用。';}
 else{document.getElementById('fontStatus').textContent='当前设置缺少 '+missing.length+' 种字体。请选择本机字体并保存。';missing.forEach(function(name,i){var field=el('div',{class:'font-replacement'}),id='replacement-'+i;field.appendChild(el('label',{for:id},'将“'+name+'”替换为'));var select=el('select',{id:id,'data-missing-font':name});select.appendChild(el('option',{value:''},'请选择本机字体'));values.forEach(function(font){select.appendChild(el('option',{value:font},font));});field.appendChild(select);replacements.appendChild(field);});document.getElementById('saveFonts').hidden=false;}
 document.getElementById('checkedAt').textContent='检查时间 '+new Date().toLocaleTimeString('zh-CN',{hour12:false});message('环境状态已更新。',false);
}
function refresh(){if(busy)return;busy=true;document.getElementById('refresh').disabled=true;document.getElementById('saveFonts').disabled=true;message('正在检查环境…',false);Promise.all([api('/environment'),api('/settings')]).then(function(results){environment=results[0];settings=results[1];render();}).catch(function(error){message((error.name==='AbortError'?'本地服务连接超时。':error.message)+' 运行 ZIP 内的检查入口，按提示重新初始化。',true);}).finally(function(){busy=false;document.getElementById('refresh').disabled=false;document.getElementById('saveFonts').disabled=false;});}
document.getElementById('refresh').onclick=refresh;document.getElementById('close').onclick=function(){window.close();};
document.getElementById('saveFonts').onclick=function(){if(busy||!settings||!environment)return;var feedback=document.getElementById('fontFeedback'),mapping={};feedback.textContent='';feedback.className='';var invalid=false;document.querySelectorAll('[data-missing-font]').forEach(function(n){if(!n.value)invalid=true;else mapping[n.dataset.missingFont]=n.value;});if(invalid){feedback.textContent='请为每种缺少的字体选择本机字体。';feedback.className='failure';return;}var config=JSON.parse(JSON.stringify(settings.current));function replace(value){if(!value||typeof value!=='object')return;Object.keys(value).forEach(function(key){if(key==='font'&&mapping[value[key]])value[key]=mapping[value[key]];else replace(value[key]);});}replace(config);busy=true;document.getElementById('saveFonts').disabled=true;document.getElementById('refresh').disabled=true;api('/settings/save',{revision:settings.revision,config:config}).then(function(next){settings=next;feedback.textContent='已保存当前设置的字体选择。回到 WPS 点击“一键排版”应用。';document.getElementById('saveFonts').hidden=true;document.getElementById('fontStatus').textContent='字体选择已保存。可重新检查确认。';}).catch(function(error){feedback.textContent='未确认保存：'+error.message+' 请重新检查设置后再尝试。';feedback.className='failure';}).finally(function(){busy=false;document.getElementById('saveFonts').disabled=false;document.getElementById('refresh').disabled=false;});};
fetch('/session').then(function(r){return r.json();}).then(function(session){token=session.token;if(!token)throw new Error('本地服务尚未连接。');refresh();}).catch(function(error){message(error.message+' 运行 ZIP 内的检查入口。',true);});
}());
