(function(){
'use strict';
var binding=new URLSearchParams(window.location.hash.slice(1)),hasClientID=binding.has('clientID'),clientID=binding.get('clientID')||'',boundDocID=binding.get('docID')||'';
document.querySelectorAll('.page-links a').forEach(function(link){link.hash=window.location.hash;});
var token='',busy=false,analysis=null,page=0,pageSize=60,closed=false,needsReanalysis=false;
var roles=[['title','标题'],['body','正文'],['addressee','称谓'],['signature','落款']];for(var i=1;i<=9;i++)roles.push(['heading'+i,i+' 级标题']);roles.push(['preserve','保持原样']);
function el(tag,props,text){var n=document.createElement(tag);Object.keys(props||{}).forEach(function(k){n.setAttribute(k,props[k]);});if(text!==undefined)n.textContent=text;return n;}
function message(text,error){var n=document.getElementById('feedback');n.textContent=text;n.className=error?'failure':'';}
function lock(value){busy=value;document.querySelectorAll('#analyze,#preview,#retry,[name=scope]').forEach(function(n){n.disabled=value;});document.querySelectorAll('#paragraphRows select').forEach(function(n){n.disabled=value||needsReanalysis;});}
function api(path,data){var controller=new AbortController(),timer=setTimeout(function(){controller.abort();},8000),headers={'Content-Type':'application/json','X-Formatter-Token':token};if(hasClientID)headers['X-Formatter-Client']=clientID;return fetch(path,{method:data===undefined?'GET':'POST',signal:controller.signal,headers:headers,body:data===undefined?undefined:JSON.stringify(data)}).then(function(r){return r.json().then(function(d){if(!r.ok||d.error)throw new Error(r.status===403?'服务已更新，请关闭后重新打开文档结构。':d.error||'本地服务无法连接。');return d;});}).finally(function(){clearTimeout(timer);});}
function command(payload){return api('/environment').then(function(environment){var status=environment.wps||environment.status||{};if(boundDocID&&(String(status.docID||'')!==boundDocID||status.documentOpen===false||status.docOpen===false))throw new Error('原文档已关闭或切换，请关闭后重新打开此窗口。');if(!status.docID)throw new Error('请先在 WPS 中打开需要操作的文档。');payload.docID=boundDocID||String(status.docID);if(hasClientID)payload.clientID=clientID;return api('/request',payload);}).then(function(request){if(!request.id)throw new Error('请求未取得编号，请重新打开文档结构。');var deadline=Date.now()+30000;function poll(){return api('/state').then(function(snapshot){var result=snapshot.result||{};if(String(result.id)===String(request.id)){if(result.ok===false)throw new Error(result.message||result.error||'WPS 请求失败。');return result;}if(Date.now()>deadline)throw new Error('等待 WPS 超时。请在 WPS 内重新打开插件并重试。');return new Promise(function(resolve){setTimeout(resolve,400);}).then(poll);});}return poll();});}
function invalidated(text){needsReanalysis=true;document.querySelector('#invalidated strong').textContent='文档已变化，请重新分析';document.getElementById('invalidated').hidden=false;document.getElementById('invalidatedMessage').textContent=text||'原有人工标记已失效。重新分析后再排版。';document.querySelectorAll('#paragraphRows select').forEach(function(n){n.disabled=true;});}
function setScope(scope){document.querySelectorAll('[name=scope]').forEach(function(n){n.checked=n.value===(scope==='selection'?'selection':'document');});}
function assignable(row){return row.assignable===undefined?row.eligible:row.assignable;}
function render(){
 var rows=analysis&&analysis.paragraphs||[],visible=rows.filter(function(row){return document.getElementById('rowFilter').value==='all'||assignable(row);});
 page=Math.max(0,Math.min(page,Math.max(0,Math.ceil(visible.length/pageSize)-1)));var body=document.getElementById('paragraphRows');body.textContent='';
 visible.slice(page*pageSize,(page+1)*pageSize).forEach(function(row){
  var tr=el('tr',{class:row.role==='preserve'?'role-original':''});tr.appendChild(el('td',{},String(row.index)));tr.appendChild(el('td',{},row.summary||'（空段）'));var role=el('td');
  if(assignable(row)){
   var select=el('select',{'aria-label':'第 '+row.index+' 段角色','data-index':String(row.index)}),blank=row.role==='blank'||!String(row.summary||'').trim();
   var options=blank?[['auto','空段（分页按规则）'],['preserve','保持原样']]:roles;
   options.forEach(function(option){select.appendChild(el('option',{value:option[0]},option[1]));});select.value=row.role==='blank'?'auto':row.role;select.disabled=busy||needsReanalysis;select.onchange=function(){updateRole(row,select.value);};role.appendChild(select);
  }else role.textContent='跳过';
  tr.appendChild(role);tr.appendChild(el('td',{},row.reason||'保持原有格式'));body.appendChild(tr);
 });
 document.getElementById('paragraphTable').hidden=!visible.length;document.getElementById('empty').hidden=visible.length>0;document.getElementById('pagination').hidden=visible.length<=pageSize;document.getElementById('previous').disabled=page===0;document.getElementById('next').disabled=(page+1)*pageSize>=visible.length;
 document.getElementById('pageSummary').textContent='第 '+(page+1)+' / '+Math.max(1,Math.ceil(visible.length/pageSize))+' 页 · '+visible.length+' 段';document.getElementById('analysisSummary').textContent=rows.filter(assignable).length+' 个普通段落 · '+rows.filter(function(row){return !assignable(row);}).length+' 个表格或其他段落';
}
function show(data){analysis=data;if(!analysis||!Array.isArray(analysis.paragraphs))throw new Error('WPS 未返回有效的段落结构。');needsReanalysis=false;setScope(analysis.scope);document.getElementById('invalidated').hidden=!analysis.sessionInvalidated;if(analysis.sessionInvalidated){document.querySelector('#invalidated strong').textContent='原有标记已清除，请检查识别结果';document.getElementById('invalidatedMessage').textContent=analysis.message||'当前识别结果已重新读取，可继续纠正角色。';}render();}
function analyze(){if(busy)return;lock(true);message('正在读取文档结构…',false);command({op:'analyze'}).then(function(result){show(result.analysis);message(result.analysis.message||'已读取。可直接修改角色；标记只在当前文档会话有效。',false);}).catch(function(error){message(error.name==='AbortError'?'本地服务连接超时，请重试。':error.message,true);}).finally(function(){lock(false);});}
function updateRole(row,role){if(busy||!analysis)return;lock(true);message('正在标记段落角色…',false);command({op:'set-role',fingerprint:analysis.fingerprint,index:row.index,role:role}).then(function(result){if(result.analysis)show(result.analysis);else return command({op:'analyze'}).then(function(next){show(next.analysis);});}).then(function(){message('角色已标记。此标记不写入文档或模板。',false);}).catch(function(error){message(error.message,true);analysis.sessionInvalidated=true;render();invalidated(error.message);}).finally(function(){lock(false);});}
document.getElementById('analyze').onclick=analyze;document.getElementById('retry').onclick=analyze;
document.querySelectorAll('[name=scope]').forEach(function(radio){radio.onchange=function(){if(busy)return;var previous=analysis&&analysis.scope||'document';lock(true);command({op:'scope',scope:radio.value}).then(function(result){if(result.analysis)show(result.analysis);else if(analysis){analysis.scope=radio.value;setScope(radio.value);}message(radio.value==='selection'?'本次按选中段落排版。点击排版时捕获选区；空选区或纯表格选区会停止。':'本次按整篇文档排版。',false);}).catch(function(error){setScope(previous);message(error.message,true);}).finally(function(){lock(false);});};});
document.getElementById('preview').onclick=function(){if(busy)return;lock(true);message('正在生成只读改动清单…',false);command({op:'preview'}).then(function(result){var preview=result.preview||{},rows=preview.rows||preview.paragraphs||[],list=document.getElementById('previewRows');list.textContent='';document.getElementById('previewSummary').textContent='范围：'+(preview.scope==='selection'?'选中段落':'整篇文档')+' · 目标 '+(preview.targetCount||0)+' 段 · 预计修改 '+((preview.counts||{}).change||0)+' 段 · 跳过 '+((preview.counts||{}).skip||0)+' 段';document.getElementById('previewWarnings').textContent=(preview.warnings||[]).join('；');rows.forEach(function(row){var li=el('li'),status=row.skip===true||row.selected===false||row.role==='preserve'||(row.skip===undefined&&row.eligible===false&&row.role!=='blank')?'跳过':row.change===false?'无需修改':'将修改';li.appendChild(el('strong',{},'第 '+row.index+' 段 · '+status+' · '+(row.summary||'（空段）')));var detail=row.changes?Array.isArray(row.changes)?row.changes.join('、'):String(row.changes):row.reason||'';li.appendChild(el('p',{},detail));list.appendChild(li);});document.getElementById('previewPanel').hidden=false;message('清单已生成，尚未修改文档。',false);}).catch(function(error){message(error.message,true);}).finally(function(){lock(false);});};
document.getElementById('rowFilter').onchange=function(){page=0;render();};document.getElementById('previous').onclick=function(){page--;render();};document.getElementById('next').onclick=function(){page++;render();};document.getElementById('closePreview').onclick=function(){document.getElementById('previewPanel').hidden=true;};document.getElementById('close').onclick=function(){closed=true;window.close();};window.addEventListener('pagehide',function(){closed=true;});
function monitor(){if(closed)return;if(!busy&&analysis)api('/environment').then(function(environment){var status=environment.wps||environment.status||{};if(boundDocID&&(String(status.docID||'')!==boundDocID||status.documentOpen===false||status.docOpen===false)){invalidated('原文档已关闭或切换，请关闭后重新打开此窗口。');message('原文档已关闭或切换，请关闭后重新打开此窗口。',true);return;}if(status.scope)setScope(status.scope);if(status.sessionInvalidated||(status.docID!==undefined&&String(status.docID)!==String(analysis.docID))){analysis.sessionInvalidated=true;invalidated(status.message);}}).catch(function(error){if(hasClientID)message(error.message,true);});setTimeout(monitor,3000);}
lock(true);fetch('/session').then(function(r){return r.json();}).then(function(session){token=session.token;if(!token)throw new Error('本地服务尚未连接。');lock(false);analyze();monitor();}).catch(function(error){message(error.message,true);lock(false);});
}());
